### ISSUE TITLE
Update connector at Metadata Broker not working

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/metadata-broker-open-core#93]
I have deployed DSCA version 7.0.1 with a local DAPS in HTTPS and set-up the Metadata Broker accrodingly.
I am able to obtain the self-description of the Metadata Broker, by this validating the local DAPS set-up.
```
2022-02-23T11:11:01,887 [https-jsse-nio-7080-exec-3] INFO - Using cached DAPS DAT. [expiration=(2022-02-23T11:44:06.000+0000)]
2022-02-23T11:11:01,914 [https-jsse-nio-7080-exec-3] INFO - Using cached DAPS DAT. [expiration=(2022-02-23T11:44:06.000+0000)]
2022-02-23T11:11:01,927 [https-jsse-nio-7080-exec-3] DEBUG - Built request message. [header=({\n  "@context" : {\n    "ids" : "https://w3id.org/idsa/core/",\n    "idsc" : "https://w3id.org/idsa/code/"\n  },\n  "@type" : "ids:DescriptionRequestMessage",\n  "@id" : "https://w3id.org/idsa/autogen/descriptionRequestMessage/34d9c229-f007-4383-976f-6db9e5831013",\n  "ids:modelVersion" : "4.2.6",\n  "ids:issued" : {\n    "@value" : "2022-02-23T11:11:01.920Z",\n    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"\n  },\n  "ids:issuerConnector" : {\n    "@id" : "https://connector_A"\n  },\n  "ids:recipientConnector" : [ {\n    "@id" : "https://broker-reverseproxy/infrastructure"\n  } ],\n  "ids:senderAgent" : {\n    "@id" : "https://connector_A"\n  },\n  "ids:securityToken" : {\n    "@type" : "ids:DynamicAttributeToken",\n    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/e9bc7514-f59e-48d2-99b5-dd503b22a949",\n    "ids:tokenValue" : "eyJ0eXAiOiJKV1QiLCJraWQiOiJkZWZhdWx0IiwiYWxnIjoiUlMyNTYifQ.eyJzY29wZXMiOlsiaWRzYzpJRFNfQ09OTkVDVE9SX0FUVFJJQlVURVNfQUxMIl0sImF1ZCI6Imlkc2M6SURTX0NPTk5FQ1RPUlNfQUxMIiwiaXNzIjoiaHR0cHM6Ly9vbWVqZG4iLCJuYmYiOjE2NDU2MTMwNDYsImlhdCI6MTY0NTYxMzA0NiwianRpIjoiTVRVek9EazVPRE0wTVRjM05USXlNREUwTWpZPSIsImV4cCI6MTY0NTYxNjY0Niwic2VjdXJpdHlQcm9maWxlIjoiaWRzYzpCQVNFX1NFQ1VSSVRZX1BST0ZJTEUiLCJyZWZlcnJpbmdDb25uZWN0b3IiOiJodHRwOi8vdGVzdGlkc2E5LmRlbW8iLCJAdHlwZSI6ImlkczpEYXRQYXlsb2FkIiwiQGNvbnRleHQiOiJodHRwczovL3czaWQub3JnL2lkc2EvY29udGV4dHMvY29udGV4dC5qc29ubGQiLCJ0cmFuc3BvcnRDZXJ0c1NoYTI1NiI6ImM2OGQ5ZTZiYTNmMTc5OWJjYmU1YmVjOWQ3ZDk4YjE1YjBlZjJmMjkyYzgwZjZiY2E5OTQxNzhhYTk1YWUxMGQiLCJzdWIiOiI2Mzo0NDpEQTpCMTpFQTozNzo1Njo4RDpFOTo4Nzo3QToyMjo3OTpEQjpBRTpEOTpFNjozOToxNDpEQjprZXlpZDpDQjo4QzpDNzpCNjo4NTo3OTpBODoyMzpBNjpDQjoxNTpBQjoxNzo1MDoyRjpFNjo2NTo0Mzo1RDpFOCJ9.mcAQocYBr24M3uT4QB0biNm2c0T8l9RL9oCgSp_Y54n8o27QtNZdxKeOVHOPduQXkKAWRkqqqSaUH9Gm7cipgFPiQ10vM88onbjw7KTnrrEDToNlOYVsWCrghOKLlOW7TkZWsNaeJYe6PJHAMKKhtX4mrWYqPVIL15ZgMkDiVJl58FP9-KAgQeujbW3dKleICdAi17vpj-2hBjN8QpUGvkC5x7gBN7LETdFzsSnoLPj3sI3qJxh6CUM59eDjz8ah0ci-3nBoZHTbNPJjIktgdHCXS20mP6kOGbA3fL_r5UmzJQj9x38ikbCRzl0lp5kvaQ1NnjsUqQGvnlEolUENCg",\n    "ids:tokenFormat" : {\n      "@id" : "https://w3id.org/idsa/code/JWT"\n    }\n  },\n  "ids:depth" : "10"\n}), payload=()]
2022-02-23T11:11:01,935 [https-jsse-nio-7080-exec-3] INFO - Sending request to https://broker-reverseproxy/infrastructure ...
2022-02-23T11:11:03,439 [https-jsse-nio-7080-exec-3] INFO - Successfully received response to request.
2022-02-23T11:11:03,464 [https-jsse-nio-7080-exec-3] INFO - Successfully passed SHACL-Validation.
2022-02-23T11:11:03,550 [https-jsse-nio-7080-exec-3] INFO - Requesting public key of token issuer. [url=(https://omejdn/.well-known/jwks.json), kid=(default)]
2022-02-23T11:11:03,609 [https-jsse-nio-7080-exec-3] INFO - Successfully verified DAT claims.
```

When I try to update the Dataspace Connector to the Metadata Broker it is giving the following error at the DSC logs:
```
2022-02-23T11:13:16,462 [https-jsse-nio-7080-exec-10] INFO - Using cached DAPS DAT. [expiration=(2022-02-23T11:44:06.000+0000)]
2022-02-23T11:13:16,482 [https-jsse-nio-7080-exec-10] INFO - Successfully loaded Keystore.
2022-02-23T11:13:16,533 [https-jsse-nio-7080-exec-10] INFO - Successfully loaded Truststore.
2022-02-23T11:13:16,538 [https-jsse-nio-7080-exec-10] INFO - Using cached DAPS DAT. [expiration=(2022-02-23T11:44:06.000+0000)]
2022-02-23T11:13:16,553 [https-jsse-nio-7080-exec-10] INFO - Sending request to https://broker-reverseproxy/infrastructure ...
2022-02-23T11:13:17,997 [https-jsse-nio-7080-exec-10] INFO - Successfully received response to request.
2022-02-23T11:13:18,006 [https-jsse-nio-7080-exec-10] INFO - Successfully passed SHACL-Validation.
2022-02-23T11:13:18,043 [https-jsse-nio-7080-exec-10] DEBUG - Received unexpected response message. [response=({reason=https://w3id.org/idsa/code/NOT_AUTHENTICATED, payload=Security profile not set, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})]
```

These are the logs obtained from the Metadata Broker:
```
broker-core            | 11:14:26.244 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.DispatcherServlet - POST "/infrastructure", parameters={masked}
broker-core            | 11:14:26.246 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Mapped to public org.springframework.http.ResponseEntity de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(java.lang.String,byte[],javax.servlet.http.HttpServletRequest) throws java.io.IOException
broker-core            | 11:14:26.250 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestPartMethodArgumentResolver - Read "application/octet-stream" to ["{
broker-core            |   "@context" : {
broker-core            |     "ids" : "https://w3id.org/idsa/core/",
broker-core            |     "idsc" : "https://w3id.org/idsa/c (truncated)...]
broker-core            | 11:14:26.251 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestPartMethodArgumentResolver - Read "application/octet-stream" to [[B@650d27bd]
broker-core            | 11:14:27.030 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
broker-core            | 11:14:27.031 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
broker-core            | 11:14:27.031 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
broker-core            | 11:14:27.032 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
broker-core            | 11:14:27.032 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
broker-core            | 11:14:27.042 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
broker-core            | 11:14:27.043 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
broker-core            | 11:14:27.043 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.TraverseAllTraversableResolver as ValidatorFactory-scoped traversable resolver.
broker-core            | 11:14:27.043 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
broker-core            | 11:14:27.043 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
broker-core            | 11:14:27.043 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
broker-core            | 11:14:27.051 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
broker-core            | 11:14:27.052 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
broker-core            | 11:14:27.053 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
broker-core            | 11:14:27.053 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
broker-core            | 11:14:27.054 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
broker-core            | 11:14:27.064 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
broker-core            | 11:14:27.064 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
broker-core            | 11:14:27.064 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.TraverseAllTraversableResolver as ValidatorFactory-scoped traversable resolver.
broker-core            | 11:14:27.064 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
broker-core            | 11:14:27.064 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
broker-core            | 11:14:27.064 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
broker-core            | 11:14:27.610 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
broker-core            | 11:14:27.610 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
broker-core            | 11:14:27.611 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
broker-core            | 11:14:27.611 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
broker-core            | 11:14:27.611 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
broker-core            | 11:14:27.626 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
broker-core            | 11:14:27.626 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
broker-core            | 11:14:27.626 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.TraverseAllTraversableResolver as ValidatorFactory-scoped traversable resolver.
broker-core            | 11:14:27.626 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
broker-core            | 11:14:27.626 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
broker-core            | 11:14:27.626 [http-nio-8080-exec-6] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
broker-core            | 11:14:27.985 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor - Found 'Content-Type:multipart/form-data' in response
broker-core            | 11:14:27.986 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor - Writing [{header=[<{
broker-core            |   "@context" : {
broker-core            |     "ids" : "https://w3id.org/idsa/core/"
broker-core            |   },
broker-core            |   "@type" : "ids:RejectionMessage",
broker-core            |   "@id" : "https://w3id.org/idsa/autogen/rejectionMessage/29122f17-985a-474f-9a5d-47d03eec94d9",
broker-core            |   "ids:securityToken" : {
broker-core            |     "@type" : "ids:DynamicAttributeToken",
broker-core            |     "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/77122fd3-4e4d-4170-8365-92eb3d8a4c17",
broker-core            |     "ids:tokenValue" : "eyJ0eXAiOiJKV1QiLCJraWQiOiJkZWZhdWx0IiwiYWxnIjoiUlMyNTYifQ.eyJzY29wZXMiOlsiaWRzYzpJRFNfQ09OTkVDVE9SX0FUVFJJQlVURVNfQUxMIl0sImF1ZCI6Imlkc2M6SURTX0NPTk5FQ1RPUlNfQUxMIiwiaXNzIjoiaHR0cHM6Ly9vbWVqZG4iLCJuYmYiOjE2NDU2MTQxNjcsImlhdCI6MTY0NTYxNDE2NywianRpIjoiTnpJNU5UZzVORFF5TWpjME1EVTROREE1IiwiZXhwIjoxNjQ1NjE3NzY3LCJzZWN1cml0eVByb2ZpbGUiOiJpZHNjOkJBU0VfU0VDVVJJVFlfUFJPRklMRSIsInJlZmVycmluZ0Nvbm5lY3RvciI6Imh0dHA6Ly90ZXN0aWRzYTEwLmRlbW8iLCJAdHlwZSI6ImlkczpEYXRQYXlsb2FkIiwiQGNvbnRleHQiOiJodHRwczovL3czaWQub3JnL2lkc2EvY29udGV4dHMvY29udGV4dC5qc29ubGQiLCJ0cmFuc3BvcnRDZXJ0c1NoYTI1NiI6IjA1OTcyZWFkMjdhYzIyYjM3ZmIzZWRjMzEwNzIzYTNhMGU3NGMwMzYwZDljMTA5YTNiOGJkMzkwZTU1ZDIyZTMiLCJzdWIiOiJDNjozRTpERToyQjpFNzowMDozRjoyQTo4NDpDMDoxRDpCRjo0MToyQzpFNjo2NTo4Mjo0NDpFODpBQzprZXlpZDpDQjo4QzpDNzpCNjo4NTo3OTpBODoyMzpBNjpDQjoxNTpBQjoxNzo1MDoyRjpFNjo2NTo0Mzo1RDpFOCJ9.X2L2rgsbhzAoyLFLOaA-i8mQRRzv0LplubCfux4zDNh9v7E6xEIjW-GG5lk3qP-Yg5CrgNWp1FepimbiHNBlBYXEkdba_OqAOf1L1SBlSTFIjA-O53VuVD6Jf_gc9r_NMsQwWtdRl04En1oOz2Sp2IbMFW_qg_TO6thxOLFp50P8-hlWKY5Ty_Q_KnFI5BPFtb55geLOjYZ0GVrD4Qo3G7afYA5bRPibT0sxW_Ze6pmKXuX44O4dPOe27_DOT08IsJKmy-yftKi3strqvO4NibJPeP12tVPr0LepJ5Un6GI5ZsSWOZ1Jt4oXQuO9eOsZdvO4O1jM0foIPSMOFO25Sw",
broker-core            |     "ids:tokenFormat" : {
broker-core            |       "@type" : "ids:TokenFormat",
broker-core            |       "@id" : "https://w3id.org/idsa/code/JWT"
broker-core            |     }
broker-core            |   },
broker-core            |   "ids:rejectionReason" : {
broker-core            |     "@type" : "ids:RejectionReason",
broker-core            |     "@id" : "https://w3id.org/idsa/code/NOT_AUTHENTICATED"
broker-core            |   },
broker-core            |   "ids:correlationMessage" : {
broker-core            |     "@id" : "https://w3id.org/idsa/autogen/connectorUpdateMessage/e9717675-eea7-4b60-81ff-2bd62742c746"
broker-core            |   },
broker-core            |   "ids:senderAgent" : {
broker-core            |     "@id" : "https://www.iais.fraunhofer.de"
broker-core            |   },
broker-core            |   "ids:issued" : {
broker-core            |     "@value" : "2022-02-23T11:14:27.606Z",
broker-core            |     "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
broker-core            |   },
broker-core            |   "ids:modelVersion" : "4.0.3",
broker-core            |   "ids:issuerConnector" : {
broker-core            |     "@id" : "https://localhost/"
broker-core            |   }
broker-core            | },{Content-Type=[application/ld+json]}>], payload=[<[B@5b47ab34,{Content-Type=[text/plain]}>]}]
broker-core            | 11:14:27.988 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.DispatcherServlet - Completed 200 OK
broker-reverseproxy    | 172.19.0.11 - - [23/Feb/2022:11:14:27 +0000] "POST /infrastructure HTTP/1.1" 200 2621 "-" "okhttp/4.9.3"
```

It seems that the security profile of the Broker is not correct and it is not working the update connector to the Broker.

**Comment by NehaThawani44** [comment]
@jfernandezsqs Please update the tag as follows and confirm if it works.

 "ids:securityProfile": {
"@id": "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE",
"@type": "ids:SecurityProfile"
},

**Comment by NehaThawani44** [comment]
this needs to be updated from connector end too, please confirm this with @tmberthold

**Comment by tmberthold** [comment]
Here is my knowledge, please correct if I see it wrong:
- DAPS DAT: `securityProfile` is part of the DAT - [see DAT mandatory securityProfile](https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/main/Components/IdentityProvider/DAPS#dynamic-attribute-token-content)
- Message-Header: In the `ConnectorUpdateMessage` itself no `SecurityProfile` is specified according to the [infomodel java artifact](https://github.com/International-Data-Spaces-Association/Java-Representation-of-IDS-Information-Model/blob/main/de/fraunhofer/iais/eis/ConnectorUpdateMessageBuilder.java)
- Message-Payload: Evaluates the entries of the [connector configuration](https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/48f15badf99bf093a2d2cbeea29605e119471789/src/main/resources/conf/config.json#L43) and adds them to the payload.

I can't see from the logs which entry is missing, the one from the DAT or the one from the payload. Would have to be evaluated at the broker, which of the two SecurityProfile entries is checked there (DAT or payload).

Note: SecurityProfile in the payload is not mandatory, because there are messages that do not have this information, for example query messages and also the responses to queries of the broker don't have this information.

**Comment by jfernandezsqs** [comment]
@NehaThawani44 I can not follow this proposed solution (https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/issues/93#issuecomment-1048682105) 
Is it supposed to be a change at the Metadata Broker? 
Can you specify the file to change in order to follow the proposed solution?
We have deployed the DAPS, DSC, App Store and Clearing House, and these components are not having this issue.

Local DAPS:
```
eyJ0eXAiOiJKV1QiLCJraWQiOiJkZWZhdWx0IiwiYWxnIjoiUlMyNTYifQ.eyJzY29wZXMiOlsiaWRzYzpJRFNfQ09OTkVDVE9SX0FUVFJJQlVURVNfQUxMIl0sImF1ZCI6Imlkc2M6SURTX0NPTk5FQ1RPUlNfQUxMIiwiaXNzIjoiaHR0cHM6Ly9vbWVqZG4iLCJuYmYiOjE2NDU2MjQ5ODUsImlhdCI6MTY0NTYyNDk4NSwianRpIjoiTkRVMU56Y3lORFUwT1RnM09EUXhOVEl5TVE9PSIsImV4cCI6MTY0NTYyODU4NSwic2VjdXJpdHlQcm9maWxlIjoiaWRzYzpCQVNFX1NFQ1VSSVRZX1BST0ZJTEUiLCJyZWZlcnJpbmdDb25uZWN0b3IiOiJodHRwOi8vdGVzdGlkc2E5LmRlbW8iLCJAdHlwZSI6ImlkczpEYXRQYXlsb2FkIiwiQGNvbnRleHQiOiJodHRwczovL3czaWQub3JnL2lkc2EvY29udGV4dHMvY29udGV4dC5qc29ubGQiLCJ0cmFuc3BvcnRDZXJ0c1NoYTI1NiI6ImM2OGQ5ZTZiYTNmMTc5OWJjYmU1YmVjOWQ3ZDk4YjE1YjBlZjJmMjkyYzgwZjZiY2E5OTQxNzhhYTk1YWUxMGQiLCJzdWIiOiI2Mzo0NDpEQTpCMTpFQTozNzo1Njo4RDpFOTo4Nzo3QToyMjo3OTpEQjpBRTpEOTpFNjozOToxNDpEQjprZXlpZDpDQjo4QzpDNzpCNjo4NTo3OTpBODoyMzpBNjpDQjoxNTpBQjoxNzo1MDoyRjpFNjo2NTo0Mzo1RDpFOCJ9.SO8qdLP0e5aqXA4rRsdTTt_Mp3sgSfhBx3FC_Bm51CjmeD6Xe0hYNtGDoyYKbUbs4_CldR-RAzxsq02IJZ0ktTI75Su7RaMLRKuS6WkPLwCUqIvZfHzmJL_qspB_kV-hW4nMWe1O2XJCx4HBHQSPAhXxFwp4vJMxqR9wf8Whr9BVFy_um29XRWSYx880cDLQqDIby3cJhNMXUSg5DZ_SD-ryv-_ntFSLS-bA3BO9AKv3gU0gXHXRkkev3RP2emNvq9PFtoc7Xpet3-7GYBVi7YPlAc4Ynva7M4V68oe2dIszSoaiKn-RqzHL8YmpRkUTmTI3vPNxQ1R6os7Jnk-pUA
```

Fraunhofer DAPS:
```
eyJ0eXAiOiJhdCtqd3QiLCJraWQiOiJUQ1VGZUNOYXphbEtIZzlLenJ6TElBelJXVE1ERFdTYTdMY005WndITXlvIiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJpZHNjOklEU19DT05ORUNUT1JTX0FMTCIsImlzcyI6Imh0dHBzOi8vZGFwcy5haXNlYy5mcmF1bmhvZmVyLmRlIiwic3ViIjoiNjM6NDQ6REE6QjE6RUE6Mzc6NTY6OEQ6RTk6ODc6N0E6MjI6Nzk6REI6QUU6RDk6RTY6Mzk6MTQ6REI6a2V5aWQ6Q0I6OEM6Qzc6QjY6ODU6Nzk6QTg6MjM6QTY6Q0I6MTU6QUI6MTc6NTA6MkY6RTY6NjU6NDM6NUQ6RTgiLCJuYmYiOjE2NDU2MjY3NDgsImlhdCI6MTY0NTYyNjc0OCwianRpIjoiT1RneE9ESTBNVFV4TWpJME1qRXlNalk1TUE9PSIsImV4cCI6MTY0NTYzMDM0OCwiY2xpZW50X2lkIjoiNjM6NDQ6REE6QjE6RUE6Mzc6NTY6OEQ6RTk6ODc6N0E6MjI6Nzk6REI6QUU6RDk6RTY6Mzk6MTQ6REI6a2V5aWQ6Q0I6OEM6Qzc6QjY6ODU6Nzk6QTg6MjM6QTY6Q0I6MTU6QUI6MTc6NTA6MkY6RTY6NjU6NDM6NUQ6RTgiLCJzZWN1cml0eVByb2ZpbGUiOiJpZHNjOkJBU0VfU0VDVVJJVFlfUFJPRklMRSIsInJlZmVycmluZ0Nvbm5lY3RvciI6Imh0dHA6Ly90ZXN0aWRzYTkuZGVtbyIsIkB0eXBlIjoiaWRzOkRhdFBheWxvYWQiLCJAY29udGV4dCI6Imh0dHBzOi8vdzNpZC5vcmcvaWRzYS9jb250ZXh0cy9jb250ZXh0Lmpzb25sZCIsInRyYW5zcG9ydENlcnRzU2hhMjU2IjoiYzY4ZDllNmJhM2YxNzk5YmNiZTViZWM5ZDdkOThiMTViMGVmMmYyOTJjODBmNmJjYTk5NDE3OGFhOTVhZTEwZCIsInNjb3BlcyI6WyJpZHNjOklEU19DT05ORUNUT1JfQVRUUklCVVRFU19BTEwiXX0.JyrODO3FngBSFTmP_I2Y0C0CV7W8LfvNqxllMjQsNUqE1ve3yP04Tyj6xIb2bU3FMuYnEcAgOlo1J0uBxTcIG3_Y6C0jQCFW88K9n8w0QO-3purWZTeFvGrRKJLDw45TR1gp8Nw1eTZgaGkHUDCFZsbl6bcif7qfe9wAXG7TzBbobA36kHcn6UKJXIy0a9p3pzZzpp6WVKVBztDcJx_v9CnGyj8mNXRb1bXdBatbDJ4prqYFx9jVjXsHaWHKSixH6rYM9bAtzukGSmjJQXN9QNu7yJUIF_JSDajSFdiaPsMGWzjAtGS6LuSKu18jjVroQsQHFEkJhVTQsQWZhU6_jg
```

These tokens can be viewed in jwt.io 
As you can see, the security profile information is the same.

**Comment by tmberthold** [comment]
could be related:
https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/pull/89#issuecomment-1036011075

**Comment by SebastianOpriel** [comment]
I had a discussion with @sebbader regarding that issue. We found out, that the securityProfile is set correctly. But due to a new infomodel version in the broker a breaking change happened, which results in the issue, you @jfernandezsqs are addressing here. In the meantime of https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/pull/89 I did not manage to check, if that solution works, yet. To not being a blocker here: @jfernandezsqs It would be great if you could check the solution of this PR. I will try my best to accept the PR until end of the week.

**Comment by jfernandezsqs** [comment]
We have tested the proposed PR, and we are facing the same issue.
 response=({reason=https://w3id.org/idsa/code/NOT_AUTHENTICATED, payload=Security profile not set, type=class de.fraunhofer.iais.eis.RejectionMessageImpl})

**Comment by SebastianOpriel** [comment]
Strange. I tested it in a local setup with DSC v7.0.2 and everything looks good so far. Switching back and forth from branch bugfix/breaking-changes-in-java-5.0.0 and master of https://github.com/International-Data-Spaces-Association/metadata-broker-open-core I am able to reproduce and fix the issue. So I can't confirm that the problem still occurs with the mentioned PR.

**Comment by jfernandezsqs** [comment]
After a meeting with Sebastian Opriel we managed to solve the issue, and the following PR fix it:
[https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/pull/89](url)

**Comment by jfernandezsqs** [comment]
Check after merge to master branch.
